# Generated by Django 6.1 on 2026-08-13 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('symptomes', models.TextField()),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField(blank=True)),
                ('health_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.healthcenter')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_patient', to=settings.AUTH_USER_MODEL)),
                ('soignant', models.ForeignKey(limit_choices_to={'role': 'soignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_soignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
