# Generated by Django 6.1 on 2026-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_centre', models.CharField(choices=[('csps', 'CSPS'), ('clinique', 'Clinique'), ('pharmacie', 'Pharmacie'), ('hopital', 'Hôpital')], max_length=15)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('est_ouvert', models.BooleanField(default=True)),
                ('horaires', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
