# Generated by Django 6.1 on 2026-08-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='gerant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'centre'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre_gere', to=settings.AUTH_USER_MODEL),
        ),
    ]
